name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          record: true
          group: '1. Resolution is high'
          env: resolution=high
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run tests in 4k resolution 🧪
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          install: false
          record: true
          group: '2. Resolution is 4k'
          env: resolution=4k
          # increase the viewport to capture more details
          config: viewportWidth=2000,viewportHeight=2000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run tests in low resolution 🧪
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          install: false
          record: true
          group: '3. Resolution is 700x600'
          env: resolution=700x600
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
