name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # allow the release step to comment on
      # issues, pull requests, and write to the repo
      contents: write
      issues: write
      pull-requests: write
      # Required for OIDC to let NPM registry know
      # that this workflow is trusted
      # https://glebbahmutov.com/blog/npm-publish-from-github/
      id-token: write

    steps:
      - name: Checkout 🛎
        # https://github.com/actions/checkout
        uses: actions/checkout@v7

      - name: Run tests in high resolution 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v7
        with:
          record: true
          group: '1. Resolution is high'
          env: resolution=high
          browser: chrome
        env:
          DEBUG: cypress-high-resolution
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run tests in 4k resolution 🧪
        uses: cypress-io/github-action@v7
        with:
          # we have already installed all dependencies above
          install: false
          record: true
          group: '2. Resolution is 4k'
          env: resolution=4k
          # increase the viewport to capture more details
          config: viewportWidth=2000,viewportHeight=2000
          browser: chrome
        env:
          DEBUG: cypress-high-resolution
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run tests in low resolution 🧪
        uses: cypress-io/github-action@v7
        with:
          # we have already installed all dependencies above
          install: false
          record: true
          group: '3. Resolution is 700x600'
          env: resolution=700x600
          browser: chrome
        env:
          DEBUG: cypress-high-resolution
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Semantic Release 🚀
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v6
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
